### ISSUE TITLE
CSS overscroll styling and min-height: 100vh

### ISSUE THREAD

**Issue by destegabry** [apexskier/camlittle.com#32]
Hi Cameron, 
I was reading your post and I found a little issue here:

> First, I want to make sure the <body> always covers the full content

So you're using `min-height: 100vh;` on the body tag. I was doing the same until I discovered that it prevents iOS Safari to hide the top and bottom bar as the user scrolls, reducing the available screen space. 

Have you found any workaround to prevent this?

**Comment by apexskier** [comment]
I'm not seeing that behavior - I still have a `min-height: 100vh` on the body, but Safari still auto-hides the toolbars for me. I also have `min-height: 100vh` on the `#wrapper` element, but that doesn't seem to matter.

I do see it on my new [photos page](http://camlittle.com/photos), but that's something I'm accepting. It's related to some hacks that I'm using to avoid iOS Safari's buggy default scroll snapping behavior.

**Comment by destegabry** [comment]
Probably the issue I am experiencing is caused by a mix of `height: 100vh` and `display: flex` on the page wrapper, containing a `flex-grow: 1` child
